### ISSUE TITLE
Unsure of entity.RecurrenceTask.java code design

### ISSUE THREAD

**Issue by anisyusof-sc** [cs2103jan2015-f13-2j/main#15]
I am unsure on how to implement the recurrrence task in code form, as shown in entity.RecurrenceTask.java. We have to discuss on how to implement it as it will affect on read/write to file.

**Comment by robobooga** [comment]
As discussed, we will make use of a JSON or similar structural design for the text file to associate recurrence tasks to the normal tasks. We definitely have to work on the actual implementation of the module itself as I foresee some issues with it. To be discussed in our next meeting.

**Comment by anisyusof-sc** [comment]
Ok. Please kindly follow up on the development of RecurrenceTask. java. Thanks.

**Comment by anisyusof-sc** [comment]
Included recurrenceDate field in entitiy.RecurrenceTask.java. Issue closed.
