### ISSUE TITLE
Check Validator.java and assist on ActionListener

### ISSUE THREAD

**Issue by anisyusof-sc** [cs2103jan2015-f13-2j/main#17]
Hi @robobooga ,

I have updated the Validator.java and included necessary codes for the "add" commands. To interpret the command:String, you may call the method "parseCommand(String)" and it will return an Object. For now, it will return a Task object (NormalTask, DeadlineTask, RecurrenceTask or FloatingTask).

What I need you to do is as follows:

1) Please kindly vet through the Validator.java and identify and possible mistakes or improvements.

2) Please kindly do up the ActionListener so that for every character input, it will call parseCommand(String) to check for correct commands. That method will throw "UnsupportedOperationException" if any of the pre-defined commands were not recognized.

Please kindly complete by Sunday, 22 FEB 2015. Do let me know if you require further assistance. Thank you.

**Comment by robobooga** [comment]
Validator looks good. 
Although it is adequate now. it may need more functions to check and parse
A rough version of ActionListener for the textbox has been done up, but there are still modifications that needs to be done to ensure the command gets parsed correctly.
