### ISSUE TITLE
Do up Logic

### ISSUE THREAD

**Issue by anisyusof-sc** [cs2103jan2015-f13-2j/main#18]
Hi @bubblegan ,

I have do up Validator.java, which currently only support "add" commands for all of Task objects (NormalTask, DeadlineTask, RecurrenceTask or FloatingTask). The only public API is "parseCommand(String)", which accept in full sentence of command (e.g. "add CE2 deadline next Friday"). That method will then return the respective Task object, depending on the type of Task.

What I need you to do is as follows:

1) Read the Validator.java carefully, and understand what the code is doing. This is important as it will have a significant impact on Logic.java if things didn't follow closely.

2) Get your logic codes ready, tuned to Validator.java and push it to the repository.

Please kindly do it by Monday, 23 FEB 2015. Do let me know if you face any issue. Thank you.

PS: @robobooga , please take note.

**Comment by bubblegan** [comment]
alright noted!

**Comment by anisyusof-sc** [comment]
Hi @bubblegan ,

I forgot to add one more task. Please consider on designing the "undo" function for this project. We might face difficulties in implementing the "undo" function if you didn't have "undo" in your mindset while designing the Logic.java.

Thanks!
