### ISSUE TITLE
Design a config file for all possible keywords/commands

### ISSUE THREAD

**Issue by anisyusof-sc** [cs2103jan2015-f13-2j/main#19]
Hi @robobooga and @bubblegan ,

We need to do up a design for a config file. Our config file will contain all possible keywords for a particular commands. 

Example:
retrieve - display, show, get, view etc.

We have to design the logic too, so that when the program initially start, it will read from the config file and load all possible commands into the application. 

Ultimately, when the program start, all possible keywords will be resolved into one and only keyword, which is either "add", "update", "retrieve" or "delete". The purpose of this is to ease the process of our application as we do not need to consider various type of alternatives for each command. On the other hand, this will provide a more user friendly environment and ease of customisability.

Please kindly think of a design so that we can implement it into our application at the soonest possible time. Thank you.

**Comment by bubblegan** [comment]
do we name the file command.txt?

**Comment by bubblegan** [comment]
and i suppose the logic flow will be

read from file > store into arrayList > use arrayList.contain() for checking??

**Comment by anisyusof-sc** [comment]
i think naming it "command.cfg" would be good. 

arrayList seems to be a good idea. but it seems inefficient as searching will take O(n). it might take a long time to seaech through large commands.

**Comment by bubblegan** [comment]
I feel using arrayList for different type of command (eg, display, add ) will be more convenient. We sacrifice optimisation for now? And we store it as GSON so for example

{"commandString":" create","commandType":"create"}
{"commandString":" add","commandType":"create"}
{"commandString":" new","commandType":"create"}

**Comment by anisyusof-sc** [comment]
Ok, I agree with your idea. I have implemented roughly similar to your description(refer to commit 96f8a83). logic.Validator will invoke a method in data.ConfigIO and load all the possible alternative commands from "command.cfg" file into the application. the only difference is that I use HashMap to store the alternative commands, instead of ArrayList. this will result in O(1) query time. all the keys will be mapped onto a single value, depending on the command.

example (key-value pair in hashmap) :
{"add":"add","create":"add","new":"add"}
