### ISSUE TITLE
designing of logic.Engine to accept display command

### ISSUE THREAD

**Issue by anisyusof-sc** [cs2103jan2015-f13-2j/main#23]
Hi @bubblegan ,

In logic.Validator, it will validate and parse a "retrieve" command, and call a function in logic.Engine. I might need you to implement several method in logic.Engine, preferably overloaded methods.

Given an example, if the method in logic.Engine is called "displayTask():List<Task>", I might need the following methods:

1) displayTask(Date dateToDisplay) - to display all Task on that particular date
e.g. retrieve 23 FEB 2015

2) displayTask(Date startDate, Date endDate) - to display all Task ranging from startDate to endDate, both inclusive.
e.g. retrieve 23 FEB 2015 to 25 FEB 2015

3) displayTask(Task task) - to display the type of Task for today only
e.g. retrieve normal/recurring/deadline/floating task

4) displayTask(Task task, Date dateToDisplay) - to display the type of Task on that date only
e.g. retrieve normal task on 23 FEB 2015

5) displayTask(Task task, Date startDate, Date endDate) - to display the type of Task from startDate to endDate, inclusive.
e.g. retrieve normal task from 23 FEB 2015 to 25 FEB 2015

6) displayTask() - retrieve all task (every single task, from the start till end of time)

Do let me know if there is any addition or issue with the suggested implementations.

**Comment by bubblegan** [comment]
we need a Comparator to sort the task in arraylist base on time for retrieval.

**Comment by anisyusof-sc** [comment]
@bubblegan Comparator added. Refer to commit #7368ad7 and entity.Task.taskComparator.

Example of usage: Collections.sort(taskList, Task.taskComparator);
