### ISSUE TITLE
Several Issues after the retrieve function implemented.

### ISSUE THREAD

**Issue by bubblegan** [cs2103jan2015-f13-2j/main#26]
Issues 1: normalTask endDate should have default value. 
- such as startDate at March 7th 2pm , if it does not indicate endDate, the endDate should be on March 7th 11:59PM

Issues 2: startDate and endDate for retrieve shouldn't indicate the exact date timing. (Should set to day_end_value )
- for example : retrieve 7 March, it will be 7 March 11:59PM instead of 7 March (current time) .

Issues 3: recurrenceTask endRecurrenceDate should have default value.
- Refer to issue 1.

Issues 4: we need priority and date.
- To fulfil query such as, retrieve urgent next week.

Issues 5: RecurrenceRetrieve not accurate. Because of various cases such as no default endRecurrence value

**Comment by anisyusof-sc** [comment]
Issue 1
Noted. I will make startDate = endDate for NormalTask & RecurrenceTask.

Issue 2
I will take a look at this, as Natty will return a Date object based on the current time, and is beyond my control. What I propose for a workaround is that, in logic.Engine, overloaded methods are for different purpose, and will extract out necessary elements that is needed.

example:
retrieveTask(Date) will only retrieve tasks that is on that day, from 0000h to 2359h. So this method will need to take out only the date(e.g. 23/02/15) and ignore the time stamp(e.g. 5.15pm), as the time is not required.

Issue 3
Same solution as issue 1

Issue 4
Perhaps you may change data.FileIO to include another parameter, priority:int . So in logic.Engine, it will have an option to either specifiy a priority, or have a wildcard (-1) to get all task with any priority.

Issue 5
Related to issue 1 and 3. Refer to solution in issue 1
