### ISSUE TITLE
usage of Object field in entity.Success

### ISSUE THREAD

**Issue by anisyusof-sc** [cs2103jan2015-f13-2j/main#32]
I believe that there is not a need for us to have Object field in entitiy.Success. To me, it seems that List<Task> would be appropriate as a replacement. Single Task object can be put into an ArrayList<Task> of size 1.

Will we be having other type of objects? Any objection?

@robobooga @bubblegan @euphy9yu

**Comment by robobooga** [comment]
Our current implementation is only using ArrayList as the object field, Therefore, I suggest we can finalize the field to be defined as an ArrayList instead of a generic object

**Comment by anisyusof-sc** [comment]
In logic.Validator, we might need to pass a String object back to application.Main. This is due to the "update" command, which in a form of "update 1". Upon this, logic.Validator will return a Task object in a form of a String for the user to update their desired field.

Hence, I conclude that we need a generic Object field in entitiy.Success class.
