### ISSUE TITLE
interval task cannot be displayed/retrieved

### ISSUE THREAD

**Issue by anisyusof-sc** [cs2103jan2015-f13-2j/main#90]
task that spans a few days cannot be retrieved/displayed properly.

example we have this task:
add task1 from 4 April 4pm to 6 April

when execute the following command:
retrieve 4 apr << task is retrieved correctly
display 4 apr << task is displayed correctly

retrieve 5 apr << above task is not retrieved
display 5 apr << above task is not displayed

**Comment by bubblegan** [comment]
solved
